variables:
  REGISTRY_ADDRESS: "registry.0zh.ru"
  GITLAB_ADDRESS: "gitlab.0zh.ru"

stages:
  - pre
  - build
  - deploy
  - post

pre-job:
  stage: pre
  image: alpine:edge
  script:
    - apk add -q bash jq
    - ls -la
    - APP_VERSION=$(jq -r .version ${CI_PROJECT_DIR}/src/package.json)
    - echo "APP_VERSION=${APP_VERSION}" > build.env
  artifacts:
    reports:
      dotenv: build.env

build-container:
  stage: build
  needs: ["pre-job"]
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - ls -la
    - echo "APP_VERSION=${APP_VERSION}"
    - CONTAINER_TAG=${APP_VERSION}
    - cp ${REGISTRY_AUTH} /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg=APP_NAME
      --destination "${REGISTRY_ADDRESS}/${REPOSITORY}/${APP_NAME}:${CONTAINER_TAG}"
    - echo "APP_VERSION=${APP_VERSION}" > build.env
    - echo "CONTAINER_TAG=${CONTAINER_TAG}" >> build.env
  artifacts:
    reports:
      dotenv: build.env

prepare-deployment:
  stage: deploy
  needs: ["build-container"]
  image: alpine:edge
  script:
    - apk add -q bash git jq
    - ls -la
    - echo "APP_VERSION=${APP_VERSION}"
    - echo "CONTAINER_TAG=${CONTAINER_TAG}"
    - |
      if [ ! -f ./kustomize/vars/${APP_VERSION}.properties ]; then
        echo -e "\e[1;33mProperties file for ${APP_NAME} version ${APP_VERSION} not exists, created from default \e[0m"
        cp ./kustomize/templates/appversion.properties.tpl ./kustomize/vars/${APP_VERSION}.properties;
      fi
    - |
      sed -e "s@APP_VERSION@${APP_VERSION}@g" \
          -e "s@CONTAINER_TAG@${CONTAINER_TAG}@g" \
          -e "s@REPOSITORY@${REPOSITORY}@g" \
          ./kustomize/templates/kustomization.yaml.tpl > ./kustomize/overlays/test/kustomization.yaml
  after_script:
    - git remote remove origin
    - git remote add origin https://oauth2:${OAUTH_TOKEN}@${GITLAB_ADDRESS}/${CI_PROJECT_PATH}.git
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git status --porcelain
    - git branch
    - git add .
    - git commit -m "Changed by CI/CD pipeline"
    - git push -o ci.skip origin HEAD:${CI_COMMIT_REF_NAME}