build-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - ls -la
    - cp ${REGISTRY_AUTH} /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry.0zh.ru/test/testapp:${APP_VERSION}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
