kind: Deployment
apiVersion: apps/v1
metadata:
  name: testapp
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testapp
  template:
    metadata:
      labels:
        name: testapp
    spec:
      imagePullSecrets:
        - name: 0zh-registry-cred
      containers:
        - name: testapp
          image: registry.0zh.ru/test/testapp:1.0.2
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          command:
            - npm
            - start
          envFrom:
            - configMapRef:
                name: testapp
          resources:
            limits:
              memory: 512Mi
              cpu: 100m
