kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: testapp
spec:
  ingressClassName: nginx
  rules:
    - host: host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapp
                port:
                  number: 8080