apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
spec:
  selector:
    matchLabels:
      app: placeholder
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
